name = "SciMLTutorialsOutput"
uuid = "a6fd76b9-682b-4eeb-9311-f9971b362b20"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "1.0.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
Documenter = "0.27"
julia = "1.6"
